FROM oven/bun:alpine

WORKDIR /app

COPY package.json bun.lockb* ./
RUN bun install

COPY . .
RUN bun run build
RUN mkdir -p dist && bunx @tailwindcss/cli -i src/index.css -o dist/index.css

EXPOSE 3000

CMD ["bun", "src/index.ts"]